//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios a este archivo pueden provocar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultar_tarjeta_T1.Account
{


    public partial class Lockout
    {
    }
}
